// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBemPqAoMUStoQpQrmIvMKaGe7MVYg6Fpc',
    appId: '1:452879867315:web:0afe925c809f0ad2aaffc6',
    messagingSenderId: '452879867315',
    projectId: 'chat-app-eba8f',
    authDomain: 'chat-app-eba8f.firebaseapp.com',
    storageBucket: 'chat-app-eba8f.appspot.com',
    measurementId: 'G-0Y7T17V1R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8dibw9ZPzyymaz8-JtkZ7nua47PEFYMw',
    appId: '1:452879867315:android:dbd1ebe954e7b44eaaffc6',
    messagingSenderId: '452879867315',
    projectId: 'chat-app-eba8f',
    storageBucket: 'chat-app-eba8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7crgzYbEkUOKkp0_oLRnIEqJWyPXXuOQ',
    appId: '1:452879867315:ios:e0c40dc99d35d437aaffc6',
    messagingSenderId: '452879867315',
    projectId: 'chat-app-eba8f',
    storageBucket: 'chat-app-eba8f.appspot.com',
    iosClientId: '452879867315-hhhgf7h9gkunjpnbkaidjshskhkg52c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7crgzYbEkUOKkp0_oLRnIEqJWyPXXuOQ',
    appId: '1:452879867315:ios:e0c40dc99d35d437aaffc6',
    messagingSenderId: '452879867315',
    projectId: 'chat-app-eba8f',
    storageBucket: 'chat-app-eba8f.appspot.com',
    iosClientId: '452879867315-hhhgf7h9gkunjpnbkaidjshskhkg52c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
